//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMentor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iMAST_dbEntities : DbContext
    {
        public iMAST_dbEntities()
            : base("name=iMAST_dbEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssignedListing> AssignedListings { get; set; }
        public virtual DbSet<iMentorRole> iMentorRoles { get; set; }
        public virtual DbSet<iMentorUser> iMentorUsers { get; set; }
        public virtual DbSet<ListingModel> ListingModels { get; set; }
    }
}
