/*
@license
dhtmlxScheduler.Net v.3.3.12 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e.form_blocks.combo={render:function(e){e.cached_options||(e.cached_options={});var t="";return t+="<div class='"+e.type+"' style='height:"+(e.height||20)+"px;' ></div>"},set_value:function(t,i,n,a){!function(){function i(){if(t._combo&&t._combo.DOMParent){var e=t._combo;e.unload?e.unload():e.destructor&&e.destructor(),e.DOMParent=e.DOMelem=null}}i();var n=e.attachEvent("onAfterLightbox",function(){i(),e.detachEvent(n)})}(),window.dhx_globalImgPath=a.image_path||"/",t._combo=new dhtmlXCombo(t,a.name,t.offsetWidth-8),
a.onchange&&t._combo.attachEvent("onChange",a.onchange),a.options_height&&t._combo.setOptionHeight(a.options_height);var s=t._combo;if(s.enableFilteringMode(a.filtering,a.script_path||null,!!a.cache),a.script_path){var r=n[a.map_to];r?a.cached_options[r]?(s.addOption(r,a.cached_options[r]),s.disable(1),s.selectOption(0),s.disable(0)):dhtmlxAjax.get(a.script_path+"?id="+r+"&uid="+e.uid(),function(e){var t=e.doXPath("//option")[0],i=t.childNodes[0].nodeValue;a.cached_options[r]=i,s.addOption(r,i),s.disable(1),
s.selectOption(0),s.disable(0)}):s.setComboValue("")}else{for(var d=[],o=0;o<a.options.length;o++){var l=a.options[o],_=[l.key,l.label,l.css];d.push(_)}if(s.addOption(d),n[a.map_to]){var h=s.getIndexByValue(n[a.map_to]);s.selectOption(h)}}},get_value:function(e,t,i){var n=e._combo.getSelectedValue();return i.script_path&&(i.cached_options[n]=e._combo.getSelectedText()),n},focus:function(e){}},e.form_blocks.radio={render:function(t){var i="";i+="<div class='dhx_cal_ltext dhx_cal_radio' style='height:"+t.height+"px;' >";

for(var n=0;n<t.options.length;n++){var a=e.uid();i+="<input id='"+a+"' type='radio' name='"+t.name+"' value='"+t.options[n].key+"'><label for='"+a+"'> "+t.options[n].label+"</label>",t.vertical&&(i+="<br/>")}return i+="</div>"},set_value:function(e,t,i,n){for(var a=e.getElementsByTagName("input"),s=0;s<a.length;s++){a[s].checked=!1;var r=i[n.map_to]||t;a[s].value==r&&(a[s].checked=!0)}},get_value:function(e,t,i){for(var n=e.getElementsByTagName("input"),a=0;a<n.length;a++)if(n[a].checked)return n[a].value;

},focus:function(e){}},e.form_blocks.checkbox={render:function(t){return e.config.wide_form?'<div class="dhx_cal_wide_checkbox" '+(t.height?"style='height:"+t.height+"px;'":"")+"></div>":""},set_value:function(t,i,n,a){t=document.getElementById(a.id);var s=e.uid(),r="undefined"!=typeof a.checked_value?i==a.checked_value:!!i;t.className+=" dhx_cal_checkbox";var d="<input id='"+s+"' type='checkbox' value='true' name='"+a.name+"'"+(r?"checked='true'":"")+"'>",o="<label for='"+s+"'>"+(e.locale.labels["section_"+a.name]||a.name)+"</label>";

if(e.config.wide_form?(t.innerHTML=o,t.nextSibling.innerHTML=d):t.innerHTML=d+o,a.handler){var l=t.getElementsByTagName("input")[0];l.onclick=a.handler}},get_value:function(e,t,i){e=document.getElementById(i.id);var n=e.getElementsByTagName("input")[0];return n||(n=e.nextSibling.getElementsByTagName("input")[0]),n.checked?i.checked_value||!0:i.unchecked_value||!1},focus:function(e){}}});