/*
@license
dhtmlxScheduler.Net v.3.3.12 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e.attachEvent("onTemplatesReady",function(){function t(e,t,n,i){for(var a=t.getElementsByTagName(e),r=n.getElementsByTagName(e),s=r.length-1;s>=0;s--){var n=r[s];if(i){var d=document.createElement("SPAN");d.className="dhx_text_disabled",d.innerHTML=i(a[s]),n.parentNode.insertBefore(d,n),n.parentNode.removeChild(n)}else n.disabled=!0,t.checked&&(n.checked=!0)}}var n=e.config.lightbox.sections.slice(),i=e.config.buttons_left.slice(),a=e.config.buttons_right.slice();e.attachEvent("onBeforeLightbox",function(t){
if(this.config.readonly_form||this.getEvent(t).readonly){this.config.readonly_active=!0;for(var r=0;r<this.config.lightbox.sections.length;r++)this.config.lightbox.sections[r].focus=!1}else this.config.readonly_active=!1,e.config.lightbox.sections=n.slice(),e.config.buttons_left=i.slice(),e.config.buttons_right=a.slice();var s=this.config.lightbox.sections;if(this.config.readonly_active){for(var r=0;r<s.length;r++)if("recurring"==s[r].type){this.config.readonly_active&&s.splice(r,1);break}for(var d=["dhx_delete_btn","dhx_save_btn"],o=[e.config.buttons_left,e.config.buttons_right],r=0;r<d.length;r++)for(var _=d[r],l=0;l<o.length;l++){
for(var c=o[l],h=-1,u=0;u<c.length;u++)if(c[u]==_){h=u;break}-1!=h&&c.splice(h,1)}}return this.resetLightbox(),!0});var r=e._fill_lightbox;e._fill_lightbox=function(){var n=this.getLightbox();this.config.readonly_active&&(n.style.visibility="hidden",n.style.display="block");var i=r.apply(this,arguments);if(this.config.readonly_active&&(n.style.visibility="",n.style.display="none"),this.config.readonly_active){var a=this.getLightbox(),d=this._lightbox_r=a.cloneNode(!0);d.id=e.uid(),t("textarea",a,d,function(e){
return e.value}),t("input",a,d,!1),t("select",a,d,function(e){return e.options.length?e.options[Math.max(e.selectedIndex||0,0)].text:""}),a.parentNode.insertBefore(d,a),s.call(this,d),e._lightbox&&e._lightbox.parentNode.removeChild(e._lightbox),this._lightbox=d,e.config.drag_lightbox&&(d.firstChild.onmousedown=e._ready_to_dnd),this.setLightboxSize(),d.onclick=function(t){var n=t?t.target:event.srcElement;if(n.className||(n=n.previousSibling),n&&n.className)switch(n.className){case"dhx_cancel_btn":
e.callEvent("onEventCancel",[e._lightbox_id]),e._edit_stop_event(e.getEvent(e._lightbox_id),!1),e.hide_lightbox()}}}return i};var s=e.showCover;e.showCover=function(){this.config.readonly_active||s.apply(this,arguments)};var d=e.hide_lightbox;e.hide_lightbox=function(){return this._lightbox_r&&(this._lightbox_r.parentNode.removeChild(this._lightbox_r),this._lightbox_r=this._lightbox=null),d.apply(this,arguments)}})});