//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMentor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
        public string Area { get; set; }
        public string Frequency { get; set; }
        public string Description { get; set; }
        public string Mentor { get; set; }
        public string URL { get; set; }
        public string Open { get; set; }
    }
}
